### ISSUE TITLE
plugin version 2.6.1 fails to install from npm sources

### ISSUE THREAD

**Issue by jeffborg** [EddyVerbruggen/Toast-PhoneGap-Plugin#114]
### Expected behaviour
Plugin should install without errors

### Actual behaviour
Cordova borks at installing the plugin see log

```
    [exec] Discovered plugin "cordova-plugin-x-toast" in config.xml. Adding it to the project
     [exec] Installing "cordova-plugin-x-toast" for android
     [exec] Error during processing of action! Attempting to revert...
     [exec] Failed to install 'cordova-plugin-x-toast': Error: Uh oh!
     [exec] ENOENT: no such file or directory, open '/Users/Shared/Jenkins/Home/jobs/biz4mobi-apps/workspace/build/hotelgosford/phonegap/plugins/cordova-plugin-x-toast/test/tests.js'
     [exec]     at Object.fs.openSync (fs.js:584:18)
     [exec]     at Object.fs.readFileSync (fs.js:491:33)
     [exec]     at install (/Users/Shared/Jenkins/Home/jobs/biz4mobi-apps/workspace/build/hotelgosford/phonegap/platforms/android/cordova/lib/pluginHandlers.js:173:36)
     [exec]     at ActionStack.process (/Users/Shared/Jenkins/Home/jobs/biz4mobi-apps/workspace/build/hotelgosford/phonegap/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
     [exec]     at PluginManager.doOperation (/Users/Shared/Jenkins/Home/jobs/biz4mobi-apps/workspace/build/hotelgosford/phonegap/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
     [exec]     at PluginManager.addPlugin (/Users/Shared/Jenkins/Home/jobs/biz4mobi-apps/workspace/build/hotelgosford/phonegap/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
     [exec]     at /Users/Shared/Jenkins/Home/jobs/biz4mobi-apps/workspace/build/hotelgosford/phonegap/platforms/android/cordova/Api.js:243:74
     [exec]     at _fulfilled (/Users/Shared/Jenkins/Home/jobs/biz4mobi-apps/workspace/build/hotelgosford/phonegap/platforms/android/cordova/node_modules/q/q.js:854:54)
     [exec]     at self.promiseDispatch.done (/Users/Shared/Jenkins/Home/jobs/biz4mobi-apps/workspace/build/hotelgosford/phonegap/platforms/android/cordova/node_modules/q/q.js:883:30)
     [exec]     at Promise.promise.promiseDispatch (/Users/Shared/Jenkins/Home/jobs/biz4mobi-apps/workspace/build/hotelgosford/phonegap/platforms/android/cordova/node_modules/q/q.js:816:13)
     [exec] Failed to restore plugin "cordova-plugin-x-toast" from config.xml. You might need to try adding it again. Error: Error: Uh oh!
     [exec] ENOENT: no such file or directory, open '/Users/Shared/Jenkins/Home/jobs/biz4mobi-apps/workspace/build/hotelgosford/phonegap/plugins/cordova-plugin-x-toast/test/tests.js'
```

### I'm seeing this behaviour on
Haven't got that far yet

### I'm not a dummy, so I've checked these
- [ X] It happens on a fresh Cordova CLI project as well.
- [ X] I'm waiting for `deviceready` to fire.
- [ X] My JavaScript has no errors (`window.onerror` catches nothing).

### So how can we reproduce this?
Install from published npm source.

**Comment by jeffborg** [comment]
See Pull request #113 for fix.
