### ISSUE TITLE
toast breaks my build

### ISSUE THREAD

**Issue by jeffmarshall** [EddyVerbruggen/Toast-PhoneGap-Plugin#14]
first: `cordova plugin add https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin.git`
second: `cordova prepare`
third: `ionic build` aaand this

```
2014-08-22 14:58:18.785 xcodebuild[58923:4203]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-5069/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:76
Details:  Failed to load dependencies output contents from ``/Users/jeff/Desktop/project-ionic/platforms/ios/build/project-ionic.build/Debug-iphonesimulator/project-ionic.build/Objects-normal/i386/Toast.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “Toast.d” couldn’t be opened because there is no such file." UserInfo=0x7f9ec73890a0 {NSFilePath=/Users/jeff/Desktop/project-ionic/platforms/ios/build/project-ionic.build/Debug-iphonesimulator/project-ionic.build/Objects-normal/i386/Toast.d, NSUnderlyingError=0x7f9ec24c3250 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/Users/jeff/Desktop/project-ionic/platforms/ios/build/project-ionic.build/Debug-iphonesimulator/project-ionic.build/Objects-normal/i386/Toast.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7f9ec73ef240>{name = (null), num = 9}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2014-08-22 14:58:18.785 xcodebuild[58923:4903]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-5069/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:76
Details:  Failed to load dependencies output contents from ``/Users/jeff/Desktop/project-ionic/platforms/ios/build/project-ionic.build/Debug-iphonesimulator/project-ionic.build/Objects-normal/i386/Toast+UIView.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “Toast+UIView.d” couldn’t be opened because there is no such file." UserInfo=0x7f9ec471ba60 {NSFilePath=/Users/jeff/Desktop/project-ionic/platforms/ios/build/project-ionic.build/Debug-iphonesimulator/project-ionic.build/Objects-normal/i386/Toast+UIView.d, NSUnderlyingError=0x7f9ec471b9d0 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/Users/jeff/Desktop/project-ionic/platforms/ios/build/project-ionic.build/Debug-iphonesimulator/project-ionic.build/Objects-normal/i386/Toast+UIView.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7f9ec471baa0>{name = (null), num = 10}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
** BUILD FAILED **


The following build commands failed:
	CompileC build/project-ionic.build/Debug-iphonesimulator/project-ionic.build/Objects-normal/i386/Toast+UIView.o project-ionic/Plugins/nl.x-services.plugins.toast/Toast+UIView.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC build/project-ionic.build/Debug-iphonesimulator/project-ionic.build/Objects-normal/i386/Toast.o project-ionic/Plugins/nl.x-services.plugins.toast/Toast.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)
Error: /Users/jeff/Desktop/project-ionic/platforms/ios/cordova/build: Command failed with exit code 65
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:755:16)
    at Process.ChildProcess._handle.onexit (child_process.js:822:5)
```

**Comment by sameera207** [comment]
Hi @jeffmarshall , I'm also getting the same error with latest ionic (v1.0.0-beta.14) and ngCordova (v0.1.10-alpha)

were you able to fix this, if so would u mind telling how ? :)

cheers

**Comment by gavhickman** [comment]
Hey @sameera207 and @jeffmarshall - I've had this issue with a few cordova plugins now.

Solution that always works for me is to add the plugin, then do:

cordova platform remove ios
cordova platform add ios

Then my build succeeds. Hope it works for you!
