### ISSUE TITLE
Android exception NoSuchMethodError setTint

### ISSUE THREAD

**Issue by mapolonio** [EddyVerbruggen/Toast-PhoneGap-Plugin#61]
Hi, i'm getting this error:
```
FATAL EXCEPTION: main
 Process: com.example.hello, PID: 24074
 java.lang.NoSuchMethodError: android.graphics.drawable.Drawable.setTint
     at nl.xservices.plugins.Toast$1.run(Toast.java:62)
     at android.os.Handler.handleCallback(Handler.java:733)
     at android.os.Handler.dispatchMessage(Handler.java:95)
     at android.os.Looper.loop(Looper.java:146)
     at android.app.ActivityThread.main(ActivityThread.java:5602)
     at java.lang.reflect.Method.invokeNative(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:515)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
     at dalvik.system.NativeStart.main(Native Method)
```
when trying to execute simple example on my device (Samsung tablet) from Android Studio

**Comment by EddyVerbruggen** [comment]
What's the minsdk and targetsdk versions of your `AndroidManifest.xml`

**Comment by EddyVerbruggen** [comment]
I've just pushed a change for this, we need to test it for Android 6 a bit, then I'll tag a new release. But you can try the master repo if you're in a hurry.

**Comment by mapolonio** [comment]
Sorry for the wait. I tried the master repo and it worked. Thanks!

**Comment by EddyVerbruggen** [comment]
:+1:
