### ISSUE TITLE
New android theme pushes crash app

### ISSUE THREAD

**Issue by roblav96** [EddyVerbruggen/Toast-PhoneGap-Plugin#62]
Ever since I updated to your newest revisions my android app crashes when I try and display a toast. Here's the logcat:
```
D/AndroidRuntime(25840): Shutting down VM
E/AndroidRuntime(25840): FATAL EXCEPTION: main
E/AndroidRuntime(25840): Process: com.testing.myapp, PID: 25840
E/AndroidRuntime(25840): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setTint(int)' on a null object reference
E/AndroidRuntime(25840): 	at nl.xservices.plugins.Toast$1.run(Toast.java:62)
E/AndroidRuntime(25840): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(25840): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(25840): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(25840): 	at android.app.ActivityThread.main(ActivityThread.java:5294)
E/AndroidRuntime(25840): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25840): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(25840): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime(25840): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
W/ActivityManager(  755):   Force finishing activity 1 com.testing.myapp/.MainActivity
I/OpenGLRenderer(  755): Initialized EGL, version 1.4
I/GCM     ( 1322): GCM message com.testing.myapp 0:1448976786964979%95de8a1af9fd7ecd
W/ActivityManager(  755): Activity pause timeout for ActivityRecord{3923f7bf u0 com.testing.myapp/.MainActivity t274 f}
```

**Comment by EddyVerbruggen** [comment]
Hey Rob,

I had that change in the codebase for about a day but indeed it requires API level 21 to run. You can now grab the 2.2.3 version which fixes this issue.

**Comment by roblav96** [comment]
Ahhh gotcha. Thanks man!!!
