### ISSUE TITLE
The plugin should not load test/tests.js file in plugin.xml

### ISSUE THREAD

**Issue by pbakondy** [EddyVerbruggen/Toast-PhoneGap-Plugin#70]
The plugin test cases are available in the final build which is contrary of "testing".

**Comment by Rakonda** [comment]
I agree with @pbakondy, test.js shouldn't be included in the build.

**Comment by EddyVerbruggen** [comment]
Can you do a PR to throw it out?

**Comment by develop161** [comment]
I'm not sure if this issue is related to the error below that I get since a week when I install this plugin:

Since a week ago I'm getting the following when I try to install this plugin:
Running command: npm install https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin.git  --save
Command finished with error code 0: npm install,https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin.git,--save
Copying plugin "../build/node_modules/cordova-plugin-x-toast" => "../build/plugins/cordova-plugin-x-toast"
Calling plugman.install on plugin "../build/plugins/cordova-plugin-x-toast" for platform "android
Installing "cordova-plugin-x-toast" for android
Running command: ../build/platforms/android/cordova/version
Command finished with error code 0: ../build/platforms/android/cordova/version
Finding scripts for "before_plugin_install" hook from plugin cordova-plugin-x-toast on android platform only.
No scripts found for hook "before_plugin_install".
Install start for "cordova-plugin-x-toast" on android.
PlatformApi successfully found for platform android
Beginning processing of action stack for android project...
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-x-toast': Error: Uh oh!
ENOENT: no such file or directory, open '../build/plugins/cordova-plugin-x-toast/test/tests.js'
    at Object.fs.openSync (fs.js:653:18)
    at Object.fs.readFileSync (fs.js:554:33)
    at install (../build/platforms/android/cordova/lib/pluginHandlers.js:173:36)
    at ActionStack.process (../build/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (../build/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:117:20)
    at PluginManager.addPlugin (../build/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:147:17)
    at ../build/platforms/android/cordova/Api.js:254:18
    at _fulfilled (../build/platforms/android/cordova/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (../build/platforms/android/cordova/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (../build/platforms/android/cordova/node_modules/q/q.js:816:13)
>> Error: Uh oh!
>> ENOENT: no such file or directory, open '../build/plugins/cordova-plugin-x-toast/test/tests.js'

I use grunt-phonegap. Strange error maybe related to the issue above, but also seems related to this issue: https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/issues/325

@EddyVerbruggen, can you please help

**Comment by albert-park** [comment]
+1
